Variables
Victoria-Stupachenko1/aqa-course-viktoriia pull request #56
Opened 2023-05-02 12:21 UTC by Victoria-Stupachenko1

2023-05-02 15:40 UTC, myevlentiev requested changes

2023-05-02 15:40 UTC, myevlentiev commented on src/OOP_tasks/User.java
> +        this.cards = new ArrayList<Cards>();
можешь додати в конструктор ось такі строки, щоб с фулнейма також записувався firstName та lastName
        this.firstName = fullName.split(" ")[0];
        this.lastName = fullName.split(" ")[1];

2023-05-03 08:18 UTC, myevlentiev requested changes

2023-05-03 08:18 UTC, myevlentiev commented on src/oop/User.java
> +        this.firstName = fullName.split (" ")[0];
Reformar Code

2023-05-03 08:18 UTC, myevlentiev commented on src/oop/User.java
> +    private ArrayList<Cards> cards = new ArrayList<> ( );  //s
// s - це навіщо ?)

2023-05-03 08:18 UTC, myevlentiev commented on src/oop/User.java
> +    private Manager manager; // s
у менеджера немає getter та setter

2023-05-03 08:18 UTC, myevlentiev commented on src/oop/User.java
> +    public void setId(int Id) {
для id сеттер не повинно бути

2023-05-03 08:18 UTC, myevlentiev commented on src/oop/User.java
> +    public User(String firstName, String lastName, String email, String role) {
а тут можешь додати щоб при використанні цього конструктора також записувалося значення в full name

2023-05-03 08:22 UTC, Victoria-Stupachenko1 commented on src/oop/User.java
> +    private ArrayList<Cards> cards = new ArrayList<> ( );  //s
Це для мене - позначка для полів, у яких мають бути сеттери

2023-05-03 15:42 UTC, myevlentiev requested changes

2023-05-03 15:42 UTC, myevlentiev commented on src/oop/Manager.java
> +        return getPhoneNumber ( );
геттер повертає не те поле )

2023-05-03 18:45 UTC, myevlentiev approved these changes

2023-05-04 07:16 UTC, merged