Java additional syntax
Victoria-Stupachenko1/aqa-course-viktoriia pull request #57
Opened 2023-05-28 17:12 UTC by Victoria-Stupachenko1

2023-05-31 13:03 UTC, myevlentiev requested changes

2023-05-31 13:03 UTC, myevlentiev commented on src/oop/Cards.java
> +            this.cardType = CardType.valueOf (String.valueOf (cardType));
reformat code

2023-05-31 13:03 UTC, myevlentiev commented on src/oop/Cards.java
> +    public Cards(String number, String expireDate, String cvv, CardType cardType) throws CardTypeExceptions {
щоб не прокидувати виключення по всім методам, можно його тут обернути в блок try catch
тоді це можно буде не писати _throws CardTypeExceptions_

2023-05-31 13:03 UTC, myevlentiev commented on src/oop/User.java
> +    public void setPhoneNumber(String phoneNumber) throws PhoneNumberValidation {
це можно не писати тут  _throws PhoneNumberValidation_, тому що виключення оброблено вже блоком try catch

2023-05-31 13:03 UTC, myevlentiev commented on src/oop/Main.java
> +        user.printInfo ( );
reformate code

2023-05-31 13:03 UTC, myevlentiev commented on src/oop/User.java
> +    public static void main(String[] args) throws UserNotFound, IOException {
це наче тут не потрібно  _throws UserNotFound, IOException_

2023-05-31 13:03 UTC, myevlentiev commented on src/interfaces/PrintInfo.java
> +    public void printInfo();
по дефолту методи в інтерфейсі і так мають модіфікатор public
так що public можно не писати, просто 
**void printInfo();**

2023-05-31 13:03 UTC, myevlentiev commented on src/oop/Manager.java
> +public class Manager extends User implements PrintInfo {
так як тут є extends від User, в якому вже реалізован метод printInfo, то мабуть тут можно не робити це
**implements PrintInfo**
а просто переопреділити метод printInfo з классу User

2023-05-31 13:03 UTC, myevlentiev commented on src/Collections/Step4Task1.java
> +    private Set<Integer> Step4Task1;
в ціломи ускаднила все )) можно було простіше, якось так наприклад, і норм було би )
![image](https://github.com/Victoria-Stupachenko1/aqa-course-viktoriia/assets/92365287/d1500541-275b-4cec-bac2-dbe9fb77b7e0)

2023-05-31 13:03 UTC, myevlentiev commented on src/Collections/Step4Task2.java
> +class Step4Task2MapExample {
зроби простіше ) щось наприкладі як в першому випадку ) нову обгортка створювати не потрібно тут

2023-05-31 13:03 UTC, myevlentiev commented on src/Collections/Step4Task3.java
> +        Collection<String> combinedCollection = new ArrayList<> ( );
для цього завдання краще обрати щось інше, щоб після об'єднання не було повторювань

2023-05-31 13:03 UTC, myevlentiev commented on users.csv
> +
файл видали) потрібно щоб створювався в процессі программи новий

2023-05-31 13:03 UTC, myevlentiev commented on src/oop/User.java
> +    public static void main(String[] args) throws UserNotFound, IOException {
цей мейн не повинен бути в середині User
спробуй виненсти реалізацію программи з Step 5. File reader/writer в окремий класс, наприклад WorkWithFile

2023-05-31 13:03 UTC, myevlentiev commented on src/interfaces/Interface4Step5.java
> +public interface Interface4Step5 {
виглядає як зайве ускладнення цей інтерфейс

2023-05-31 13:03 UTC, myevlentiev commented on src/interfaces/PrintInfo.java
> +    String userData();
виглядає як зайве ускладнення

2023-06-01 21:28 UTC, myevlentiev requested changes

2023-06-01 21:28 UTC, myevlentiev commented on src/oop/Cards.java
>  public class Cards {
правильніше буду назвати класс Card, так як це шаблон для оної картки

2023-06-01 21:28 UTC, myevlentiev commented on src/oop/Cards.java
> +    public Cards(String number, String expireDate, String cvv, CardType cardType) throws CardTypeExceptions {
все ж таки виходить, що якщо ти передаєшь значення через enum, то тут не потрібно виключення, так як через ENUM ти зможен передати тільки два варіанти, які там вказала, тобто VISA або MasterCard, третього не дано, тому все що повязано з цим ексепшином и сам ексепшин можно видалили все ж таки **CardTypeExceptions**

2023-06-01 21:28 UTC, myevlentiev commented on src/oop/Main.java
> +        user.addCard("4142567898764567", "02/24", "123", Cards.CardType.valueOf("VISA"));
user.addCard("4142567898764567", "02/24", "123", **Card.CardType.VISA**);
    user.addCard("41425678723764567", "02/28", "123", **Card.CardType.MASTERCARD**);

2023-06-01 21:28 UTC, myevlentiev commented on src/oop/Cards.java
> +            this.cardType = CardType.valueOf (String.valueOf (cardType));
ok

2023-06-01 21:28 UTC, myevlentiev commented on src/oop/User.java
> +                throw new IllegalArgumentException("Phone number must start with '+'");
**IllegalArgumentException** - це не твій кастомний ексепшин який ти написала ) тобі потрібен твій **PhoneNumberValidation**
ось приклад як можно спробувати обробити
![image](https://github.com/Victoria-Stupachenko1/aqa-course-viktoriia/assets/92365287/c7e449d0-b41b-4f1e-b53a-4ea359c6d177)

2023-06-01 21:28 UTC, myevlentiev commented on src/interfaces/PrintInfo.java
> +    public void printInfo();
тут можешь видалити public )

2023-06-01 21:28 UTC, myevlentiev commented on src/oop/Manager.java
> + //   public void printUserInfo() {
таке зазвичай просто замусорює код, то краще видаляти таке

2023-06-01 21:28 UTC, myevlentiev commented on src/oop/Manager.java
> +public class Manager extends User implements PrintInfo {
Так як метод printInfo в тебе не реалізується з інтерфесу, то це можно видалити implements PrintInfo

2023-06-01 21:28 UTC, myevlentiev commented on src/oop/Manager.java
> +        System.out.println(position + ", " + responsibilityDistrict + ", " + workPhoneNumber);
так виведеться не повна інформація, додай ось так
        **super.printInfo();** - щою вивести також поля які є у User
        System.out.println(position + ", " + responsibilityDistrict + ", " + workPhoneNumber);

2023-06-01 21:28 UTC, myevlentiev commented on src/Collections/Step4Task3.java
> +        Collection<String> combinedCollection = new ArrayList<> ( );
не запускається ) помилка )
![image](https://github.com/Victoria-Stupachenko1/aqa-course-viktoriia/assets/92365287/38a3002d-1801-4532-a5ca-baccd6829d3b)

2023-06-03 17:11 UTC, Victoria-Stupachenko1 commented on src/oop/Cards.java
> +    public Cards(String number, String expireDate, String cvv, CardType cardType) throws CardTypeExceptions {
Внесла зміни

2023-06-03 17:11 UTC, Victoria-Stupachenko1 commented on src/oop/User.java
> +    public void setPhoneNumber(String phoneNumber) throws PhoneNumberValidation {
Прибрала зайве

2023-06-03 17:11 UTC, Victoria-Stupachenko1 commented on src/oop/Main.java
> +        user.printInfo ( );
Зробила реформат

2023-06-03 17:12 UTC, Victoria-Stupachenko1 commented on src/Collections/Step4Task2.java
> +class Step4Task2MapExample {
Спростила)

2023-06-03 17:12 UTC, Victoria-Stupachenko1 commented on src/Collections/Step4Task3.java
> +        Collection<String> combinedCollection = new ArrayList<> ( );
Внесла зміни

2023-06-03 17:12 UTC, Victoria-Stupachenko1 commented on src/interfaces/PrintInfo.java
> +    String userData();
прибрала String userData();

2023-06-03 17:12 UTC, Victoria-Stupachenko1 commented on src/oop/Cards.java
>  public class Cards {
Переіменувала клас на Card

2023-06-03 17:13 UTC, Victoria-Stupachenko1 commented on src/oop/User.java
> +                throw new IllegalArgumentException("Phone number must start with '+'");
Внесла зміни

2023-06-03 17:13 UTC, Victoria-Stupachenko1 commented on src/oop/Manager.java
> + //   public void printUserInfo() {
Видалила

2023-06-07 10:03 UTC, myevlentiev approved these changes

2023-06-12 19:56 UTC, merged